project_id = "omoumaimise-map"

[api]
enabled = true
port = 13321

[db]
port = 23322

[db.seed]
enabled = true
sql_paths = ["./seeds/*.sql"]

[studio]
enabled = true
port = 13323

[inbucket]
enabled = true
port = 13324
