project_id = "omoumaimise-map"

[api]
enabled = true
port = 13421

[db]
port = 23422

[db.seed]
enabled = true
sql_paths = ["./seeds/*.sql"]

[studio]
enabled = true
port = 13423

[inbucket]
enabled = true
port = 13424
